// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aigziyoudlplrgxorjlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpZ3ppeW91ZGxwbHJneG9yamx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjU1MjYsImV4cCI6MjA1ODg0MTUyNn0.Osisqxw0u7wXdBVrs03Er7BCvaTSiUvzPYL1-2hh2SU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);